services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin123}
      - ADMIN_TOKEN_SECRET=${ADMIN_TOKEN_SECRET:-somerandomsecret123}
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./server/dev.db:/app/dev.db
    networks:
      - smartnet


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - smartnet

networks:
  smartnet:
    driver: bridge
