  test-api-blackbox:
    name: Tests API (caja negra con Docker Compose v2)
    runs-on: ubuntu-latest
    needs: [build-images]
    steps:
      - uses: actions/checkout@v4

      # Levantar stack con compose v2
      - name: Boot stack
        run: docker compose up -d

      - name: Esperar backend /health
        run: |
          for i in {1..40}; do
            if curl -fsS http://localhost:3001/health >/dev/null; then
              echo "Backend OK"; exit 0
            fi
            echo "Esperando backend... ($i)"
            sleep 3
          done
          echo "Backend no respondió a tiempo" >&2
          exit 1

      - name: Instalar deps de tests (server)
        run: npm ci
        working-directory: server

      - name: Ejecutar tests API
        env:
          BASE_URL: http://localhost:3001
          NODE_ENV: test
          ADMIN_USER: admin
          ADMIN_PASS: admin123
        run: npm test
        working-directory: server

      - name: Logs si falla
        if: failure()
        run: |
          docker compose ps
          docker compose logs --no-color backend || true
          docker compose logs --no-color frontend || true

      - name: Down
        if: always()
        run: docker compose down -v
